### ISSUE TITLE
Simplify build and test scripts

### ISSUE THREAD

**Issue by pomadchin** [azavea/azavea.g8#52]
At this point bloop is used in the CI. However, it looks like it is more a user development part of the project. 
CI can be more agnostic and rely on SBT only. Moreover, SBT 1.4 uses BSP as an alternative to Bloop by default.

How do you feel about making CI only with SBT and the default local dev worflow will be pretty much default in this case?

```bash
$ sbt
$ sbt> ;compile; test; etc...
``` 

P.S.

Metals usage does not require an _explicit_ bloop usage. It is used and added by default into the project during the project import into metals via VSCode. 

`metals.sbt` generated during such import is usually ingored and not a part of the repository.

**Comment by jisantuc** [comment]
This is a good idea and would be helpful. `bloop` crept in here specifically because it was the only build server that was supported when Metals shipped. However, recent versions of sbt (>=1.4) have build server protocol support, and later versions of metals support both bloop and sbt's build server protocol implementation. There are more details about that [here](https://scalameta.org/metals/blog/2020/11/06/sbt-BSP-support.html). I've done the steps in that post in my local Franklin and have noticed two things --

1. everything Just Works :tm:
2. Warnings now include scapegoat! I think that's a sign that sbt's bsp implementation gives us access to warnings from more or less arbitrary sbt plugins that we have enabled.

We were pretty much forced to use `bloop` with Metals initially, and now that we're not anymore, we should unify the compilation / assembly experience with a single build tool. Since we use sbt for access to the sbt plugins we use in CI and for packaging, I think the single tool should be sbt.

**Comment by pomadchin** [comment]
Up!

**Comment by pomadchin** [comment]
Closed in https://github.com/azavea/azavea.g8/pull/54
